config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

  get 'likes/delete'

  get 'bright_ideas/index'

  get 'bright_ideas/create'

  get 'bright_ideas/show'

  get 'bright_ideas/delete'

  get 'users/index'

  get 'users/create'

  get 'users/show'

  get 'sessions/create'

  get 'sessions/destroy'
  
  post 'login' => 'sessions#create'

root 'application#index'
post 'users' => 'users#create'
 get 'users/:id' => 'users#show'
 get 'bright_ideas' => 'bright_ideas#index'
 post 'bright_ideas' =>'bright_ideas#create'
 get 'delete/:idea_id' => 'bright_ideas#delete'
get 'like/:idea_id' => 'likes#create'
get 'unlike/:idea_id' => 'likes#delete'
get 'bright_ideas/:id' => 'bright_ideas#show'

end

app/models/bright_idea.rb
class BrightIdea < ActiveRecord::Base
  
  belongs_to :user

  has_many :likes
  has_many :users, through: :likes
  validates :content, presence: true, length: 2..30

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bright_idea
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save :downcase_fields

  has_many :bright_ideas, dependent: :destroy, source: :bright_idea
  has_many :likes
  has_many :ideas_liked, through: :likes, source: :bright_idea

  validates :name, :alias, presence: true, length: 2..30
  validates :alias, uniqueness: true 
  validates_format_of :name, :alias, with: /\A[-a-z]+\Z/i
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  	def downcase_fields
		self.name.downcase!
		self.alias.downcase!
		self.email.downcase!
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #This index renders registration
  def index
  	if current_user
  		redirect_to '/bright_ideas/'
  	end
  end

  def current_user
    return User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/bright_ideas_controller.rb
class BrightIdeasController < ApplicationController
	before_action :user_logged
  def index
  	@all_ideas = BrightIdea.all
  	@ideas = BrightIdea.find_by_sql("select bright_ideas.id, count(*) as total_likes from bright_ideas left join likes on bright_ideas.id = likes.bright_idea_id group by bright_ideas.id order by count(*) desc")
  	
  end

  def create
  	idea = BrightIdea.new(content: params[:content], user_id: current_user.id)
  	if idea.valid?
  		idea.save
  		return redirect_to "/bright_ideas"
  	else
  		flash[:errors] = idea.errors.full_messages
  		return redirect_to :back
  	end
  end

  def show
  	@idea = BrightIdea.find(params[:id])

  end

  def delete
  	@idea = BrightIdea.find_by_id(params[:idea_id].to_i)
  	if @idea
	  	if @idea.user_id == current_user.id
	  		@idea.destroy
	  		return redirect_to :back
	  	else
	  		flash[:errors] = ["Cannot delete idea you did not post!"]
	  		return redirect_to '/'
	  	end
	else
		flash[:errors] =["That idea is not found"]
	end	
  	return redirect_to '/'
  end
  private
  	def user_logged
  	if !current_user
  		return redirect_to '/'
  	end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
  	@did_like = Like.find_by_sql("select * from likes where bright_idea_id = #{params[:idea_id].to_i} and user_id = #{current_user.id.to_i}")
  	
  	if @did_like.length > 0
  		flash[:errors] = ["This post has already been liked"]
  		return redirect_to '/'
  	else
  		liked = Like.create(user_id: current_user.id, bright_idea_id: params[:idea_id])
  		return redirect_to '/'
  	end	
  	
  	return redirect_to '/'
  end

  def delete
  	@did_like = Like.find_by_sql("select * from likes where bright_idea_id = #{params[:idea_id].to_i} and user_id = #{current_user.id.to_i}")
  	
  	if @did_like.length == 0
  		flash[:errors] = ["This post has already been unliked"]
  		return redirect_to '/'
  	else
  		@did_like.first.destroy
  		return redirect_to '/'
  	end	
  	
  	return redirect_to '/'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	@user = User.find_by_email(params[:email])
  	if @user
  		if @user.try(:authenticate, params[:password])
  			session[:user_id] = @user.id
  			return redirect_to '/bright_ideas/'
  		end
  	else
  		flash[:errors] = ["Invalid credentials"]
  		
  	end
  	flash[:errors] = ["Invalid credentials"]
  	return redirect_to :back
  end

  def destroy
  	session.clear
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate, only: [:show]
  def index
  end

  def create
  	@find_user = User.find_by_email(user_params[:email])
  	if @find_user
  		flash[:errors] = ["That email address has been registered"]
  		return redirect_to :back
  	else
  		@user = User.new(user_params)
  		if @user.valid?
  			@user.save
  			session[:user_id] = @user.id
  			redirect_to "/bright_ideas/"
  		else	
  			flash[:errors] = @user.errors.full_messages
  			return redirect_to :back
  		end	
  	end
  end

  def show
  	@view_user = User.select("name, alias, email, id").find(params[:id])
  	
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :alias, :email, :password, :password_confirmation)
  	end

  	def authenticate
  		if current_user
		            if params[:id] != current_user.id
			end
		else
			return redirect_to '/'
		end
   	 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bright_ideas_helper.rb
module BrightIdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<div class="row">
<div class="col-1"></div>
	<div class="col-10">
		<% if flash[:errors] %>
			<% flash[:errors].each do |message| %>
			<p style="color:red"><%= message %></p>
			<% end %>
		<% end %>
	</div>
</div>

<div class="row">
	<div class="col-1"></div>
	<!-- Register Form -->
	<div class="col-5">
		<h2>Register</h2>
		<form action="/users" method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />

			<div class="form-group">
				<label for="name">Name:</label>
				<input type="text" name="user[name]" id="name" class="form-control" />
					
			</div>

			<div class="form-group">
				<label for="alias">Alias:</label>
				<input type="text" name="user[alias]" id="alias" class="form-control" />
			</div>

			<div class="form-group">
				<label for="email">Email:</label>
				<input type="email" name="user[email]" id="email" class="form-control" />
			</div>

			<div class="form-group">
				<label for="password">Password:</label>
				<input type="password" name="user[password]" id="password" class="form-control" />
			</div>

			<div class="form-group">
				<label for="password_confirmation">Password Confirmation:</label>
				<input type="password" name="user[password_confirmation]" id="password_confirmation" class="form-control" />
			</div>

			<button type="submit" class="btn btn-primary">Register</button>
		</form>
	</div>
	<!-- End Registration Form -->
	<!-- Login Form -->
	<div class="col-5">
		<h2>Login</h2>
		<form action="/login" method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />

			<div class="form-group">
				<label for="email">Email:</label>
				<input type="email" name="email" id="email" class="form-control" />
			</div>

			<div class="form-group">
				<label for="password">Password:</label>
				<input type="password" name="password" id="password" class="form-control" />
			</div>

			<button type="submit" class="btn btn-primary">Login</button>
		</form>
	</div>
	<!-- End Login Form -->
	<div class="col-1"></div>
</div>

app/views/bright_ideas/create.html.erb
<h1>BrightIdeas#create</h1>
<p>Find me in app/views/bright_ideas/create.html.erb</p>

app/views/bright_ideas/delete.html.erb
<h1>BrightIdeas#delete</h1>
<p>Find me in app/views/bright_ideas/delete.html.erb</p>

app/views/bright_ideas/index.html.erb
<%= link_to 'Logout', sessions_destroy_path %>
<br><br>
<h4>Hi, <%= current_user.name.titleize %>!</h4>
<br>
<div class="row">
<div class="col-1"></div>
	<div class="col-10">
		<% if flash[:errors] %>
			<% flash[:errors].each do |message| %>
			<p style="color:red"><%= message %></p>
			<% end %>
		<% end %>
	</div>
</div>

<div class="row">
	<div class="col-1"></div>
	<!-- Register Form -->
	<div class="col-6">
		<form action="/bright_ideas" method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />

			<div class="form-group">
				
				<input style="display:inline-block" type="content" name="content" id="content" class="form-control" placeholder="Post something witty here...">

				<button style="display:inline-block" type="submit" class="btn btn-primary">Idea!</button>
			</div>
			
		</form>
	</div>
	
	<div class="col-1"></div>
</div>
<!-- Start of all idea post -->

<div class="row">
	<div class="col-1"></div>
	<!-- Register Form -->
	<div class="col-6">
		
			<% @ideas.each do |count|%>
			<% @all_ideas.each do |idea|%>
			<% if count.id == idea.id %>
			<p>
			<a href="/users/<%= idea.user_id %>"><%= idea.user.name.titleize %></a>
			says: <%= idea.content %>
			 

			<% if idea.user_id == current_user.id %>
				<a href="/delete/<%= idea.id %>">Delete</a>
			<% end %>
			<br>
			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
			<% unless current_user.ideas_liked.include? idea %>
				<a href="/like/<%= idea.id %>">Like</a>
			<% else %>
				<a href="/unlike/<%= idea.id %>">Unlike</a>
			<% end %>|
			<a href="/bright_ideas/<%= idea.id %>"><%= idea.likes.count %> people</a> like this.
			
			</p>
			<br>
			<% end %>
			<% end %>
			<% end %>
	</div>
	
	<div class="col-1"></div>
</div>

app/views/bright_ideas/show.html.erb
<div class="row">


<div class="col-6"></div>
	<div class="col-13">
		<a href="/bright_ideas">Bright Ideas</a>
		<%= link_to 'Logout', sessions_destroy_path %>

	</div>

</div>

<div class="row">
<div class="col-1"></div>

	<div class="col-5">
	<p>
	<a href="/users/<%= @idea.user_id %>"><%= @idea.user.name.titleize %></a>
	says: <%= @idea.content %>
	</p>
</div>	
</div>


<div class="row">
<div class="col-1"></div>

	<div class="col-5">
	<h4>People who liked this post:</h4>
	<table>
		<tr>
			<th>Alias</th>
			<th>Name</th>
		</tr>
		<% @idea.likes.each do |users_liked|  %>
		<tr>
			<td><a href="/users/<%= users_liked.user.id %>"><%= users_liked.user.alias.titleize %></a></td>
			<td><%= users_liked.user.name.titleize %></td>
		</tr>
		<% end %>
	</table>
</div>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeltExam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/delete.html.erb
<h1>Likes#delete</h1>
<p>Find me in app/views/likes/delete.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="row">


<div class="col-6"></div>
	<div class="col-13">
		<a href="/bright_ideas">Bright Ideas</a>
		<%= link_to 'Logout', sessions_destroy_path %>

	</div>
</div>
<div class="row">
<div class="col-1"></div>

	<div class="col-5">
	<hr style="border-width: 5px;">
		<p>Name: <%= @view_user.name %></p>
		<p>Alias: <%= @view_user.alias %></p>
		<p>Alias: <%= @view_user.email %></p>
		<hr style="border-width: 5px;">
		<p>Total number of post: <%= @view_user.bright_ideas.count %></p>
		<p>Total number of likes: <%= @view_user.likes.count %></p>
	</div>
		

</div>